language: node_js
node_js:
  - "node"
script: npm run build:all && npm run build:docs
deploy:
  tag: next
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master
  provider: npm
    email: "yordilorenzo@gmail.com"
    api_key: $NPM_TOKEN    
cache:
  directories:
    - "node_modules"    