language: node_js
node_js:
  - "node"
before_script:
  - npm install
script: npm run build:docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
cache:
  directories:
    - "node_modules"    